#!/usr/bin/env python3
# DESCRIPTION: Verilator: Verilog Test driver/expect definition
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of either the GNU Lesser General Public License Version 3
# or the Perl Artistic License Version 2.0.
# SPDX-FileCopyrightText: 2026 Tom and contributors
# SPDX-License-Identifier: LGPL-3.0-only OR Artistic-2.0
#
# Regression test for issue #5756: data race on global edge ID counter
# in V3TSP::tspSort when using --verilate-jobs.
#
# Each generated module has multiple independent always blocks so the MTask
# partitioner creates diverse affinity patterns, producing non-trivial TSP
# graphs in V3VariableOrder. With --verilate-jobs, multiple modules run
# tspSort concurrently, exercising the (formerly racy) edge ID counter.

import vltest_bootstrap

test.scenarios('vltmt')
test.top_filename = test.obj_dir + "/t_verilate_jobs_tsp.v"

NUM_MODULES = 200
NUM_CHAINS = 6
CHAIN_LEN = 8
OPS = ['^', '+', '-']


def gen(filename):
    with open(filename, 'w', encoding="utf8") as f:
        f.write("// Generated by t_verilate_jobs_tsp.py\n")
        for idx in range(NUM_MODULES):
            _gen_module(f, idx)
        _gen_top(f, NUM_MODULES)


def _gen_module(f, idx):
    name = f"tsp_mod_{idx:03d}"
    last = CHAIN_LEN - 1
    f.write(f"module {name}(\n")
    f.write(f"    input wire clk,\n")
    f.write(f"    input wire [7:0] seed,\n")
    f.write(f"    output wire [7:0] out\n")
    f.write(f");\n")

    chain_names = []
    for c in range(NUM_CHAINS):
        ch = chr(ord('a') + c)
        chain_names.append(ch)
        for r in range(CHAIN_LEN):
            pub = " /*verilator public*/" if r == last else ""
            f.write(f"    reg [7:0] {ch}{r}{pub};\n")
        f.write(f"    always @(posedge clk) begin\n")
        c0 = (idx * 13 + c * 47 + 1) & 0xFF
        f.write(f"        {ch}0 <= seed {OPS[(idx + c) % 3]} 8'h{c0:02X};\n")
        for r in range(1, CHAIN_LEN):
            const = (idx * 13 + c * 47 + r * 37 + 1) & 0xFF
            f.write(f"        {ch}{r} <= {ch}{r-1} {OPS[(idx + c + r) % 3]} 8'h{const:02X};\n")
        f.write(f"    end\n")

    # Cross-chain combinational logic for diverse MTask affinities
    f.write(f"    // Cross-chain combinational\n")
    cross = []
    for i in range(NUM_CHAINS - 1):
        ca, cb = chain_names[i], chain_names[i + 1]
        w = f"x_{ca}{cb}"
        f.write(f"    wire [7:0] {w} = {ca}{last} {OPS[(idx + i) % 3]} {cb}{last};\n")
        cross.append(w)
    stride2 = []
    for i in range(0, NUM_CHAINS - 2, 2):
        ca, cc = chain_names[i], chain_names[i + 2]
        w = f"x_s2_{ca}{cc}"
        f.write(f"    wire [7:0] {w} = {ca}{last} {OPS[(idx + i + 1) % 3]} {cc}{last};\n")
        stride2.append(w)
    quads = []
    for i in range(0, len(cross) - 1, 2):
        w = f"x_q_{i}"
        f.write(f"    wire [7:0] {w} = {cross[i]} {OPS[(idx + i + 2) % 3]} {cross[i+1]};\n")
        quads.append(w)
    mixed = []
    for i in range(min(len(quads), len(stride2))):
        w = f"x_m_{i}"
        f.write(f"    wire [7:0] {w} = {quads[i]} {OPS[(idx + i) % 3]} {stride2[i]};\n")
        mixed.append(w)
    all_r = mixed + quads[len(mixed):] + stride2[len(mixed):]
    if not all_r:
        all_r = cross
    result = all_r[0]
    for i in range(1, len(all_r)):
        w = f"x_r_{i}"
        f.write(f"    wire [7:0] {w} = {result} {OPS[(idx + i) % 3]} {all_r[i]};\n")
        result = w
    f.write(f"    assign out = {result};\n")
    f.write(f"endmodule\n")


def _gen_top(f, n):
    f.write("module t(clk);\n")
    f.write("    input clk;\n")
    f.write(f"    wire [7:0] w [0:{n}];\n")
    f.write(f"    assign w[0] = 8'hA5;\n")
    for idx in range(n):
        f.write(f"    tsp_mod_{idx:03d} u_{idx:03d}"
                f" (.clk(clk), .seed(w[{idx}]), .out(w[{idx+1}]));\n")
    f.write("    integer cyc = 0;\n")
    f.write("    always @(posedge clk) begin\n")
    f.write("        cyc <= cyc + 1;\n")
    f.write("        if (cyc == 10) begin\n")
    f.write('            $write("*-* All Finished *-*\\n");\n')
    f.write("            $finish;\n")
    f.write("        end\n")
    f.write("    end\n")
    f.write("endmodule\n")


gen(test.top_filename)

# threads=6: enable MTasks mode with enough threads for diverse affinities
# --verilate-jobs 6: process modules in parallel (concurrent tspSort calls)
# -fno-inline: prevent module flattening so each module is ordered separately
test.compile(verilator_flags2=["--verilate-jobs 6", "-fno-inline"], threads=6)

test.execute()

test.passes()
